---
- name: Terminate tagged instances
  # hosts: tag_{{ tag_name }}_{{ tag_value }}
  # execution: ansible-playbook -e tag_name=Name -e tag_value=web_server terminate.yml
  hosts: local
  tasks:
      
    - name: Destroying the Current Running Instances
      ec2_instance:
        state: absent
        filters:
          instance-state-name: running
        tags:
          name: "ITBR-INFRA"  

    - name: "Delete group by name {{ SG_NAME}}"
      ec2_group:
        name: "{{ SG_NAME }}"
        state: absent

    - name: Delete Dinamic Public IPs from Hosts File
      lineinfile:
        path: "hosts"
        state: absent
        regexp: '^.*[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
  
      
