---
- name: Install and start Apache
  hosts: webserver
  connection: local

  tasks:
  - name: Install Repo
    yum: name=epel-release state=present

  - name: install python binding Selinux
    yum: name={{item}} state=present
    with_items: 
    - libselinux-python
    - libsemanage-python

  - name: test if Selinux is running
    command: getenforce
    register: sestatus
    changed_when: false

  - name: install apache
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - httpd
      - httpd-tools

  - name: restart Apache Services
    service:
       name: httpd
       state: present
       enabled: yes    
