- name: "Setting Security Groups"
  local_action:
    module: ec2_group
    name: "{{ SG_NAME }}"
    description: "AWS SG Default Group - IT.BR"
    region: "{{ AWS_REGION }}"
    rules:
      - proto: tcp
        ports:
        - 22
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 22 and  80 
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
        # description to use if example-other needs to be created
        group_desc: "Egress rule Firewall - IT.BR"
  register: basic_firewall

- name: "Creating AWS Instances"
  local_action:
    module: ec2
    key_name: "{{ KEYPAIR_NAME }}"
    instance_type: "{{ INSTANCE_TYPE }}"
    image: "{{ AMI_IMAGE }}"
    wait: yes
    group: "{{ INSTANCE_GROUP }}"
    count: "{{ INSTANCES_NUMBER }}"
    # assign_public_ip: yes 
  register: ec2.logs.create

- name: "Creating Temp Inventory"
  add_host:
    name: "{{ item.public_ip }}" 
    groups: itbr-aws-instances
  with_items: "{{ ec2.intances }}"
  
- name: Generate Dinamic Inventory 
  lineinfile:
      path: "./hosts"
      regexp: "{{ item.public_ip }}"
      insertafter: '[itbr-aws-instances]'
      line: "{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"


- name: Wait Instances get Ready
  wait_for: 
      host: "{{ item.public_ip }}"
      port: 22
      state: started
  with_items: "{{ ec2.instances }}"  

- name: Setting Instance TAG 
  ec2_tag:
    region: "{{ AWS_REGION }}"
    resource: "{{ item.id }}"
    state: present
    tags:
      Name: ITBR-INFRA
  with_items: "{{ ec2.instance }}"
      